require: rubocop-rspec

inherit_from:
  - https://raw.githubusercontent.com/psu-stewardship/guides/master/style/ruby/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.3

RSpec/DescribeClass:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/routing/**/*'
    - 'spec/rake/**/*'
    - 'spec/config/**/*'
    - 'spec/models/batch_spec.rb'
    - 'spec/features/**/*'
    - 'spec/support/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/models/**/*'
    - 'lib/tasks/**/*'
    - 'app/controllers/catalog_controller.rb'
    - 'config/deploy.rb'
